### ISSUE TITLE
Please support Tensor Comprehensions on macOS

### ISSUE THREAD

**Issue by rahulbhalley** [facebookresearch/TensorComprehensions#104]
Please support Tensor Comprehensions on macOS
----------------------------------------------

Please consider the following information:
- OS: macOS 10.13.3
- How you installed TC (docker, conda, source): could not install (not supported)
- Python version: 2.7.x
- Conda version (is using conda): 4.4.11

**Comment by prigoyal** [comment]
Thanks @rahulbhalley, we don't have any concrete plans yet for this but can you provide some info why macOS? we can look into prioritizing this and we also warmly welcome any contributions :)

**Comment by rahulbhalley** [comment]
I find that CUDA is not supported on AMD but OpenCL so closing this issue for now.
