### ISSUE TITLE
Deadlock in Autotuner 

### ISSUE THREAD

**Issue by prigoyal** [facebookresearch/TensorComprehensions#108]
we have an interesting use case where autotuner deadlocks. 
here is gdb backtrace: https://gist.github.com/prigoyal/3a50a60c79fc1e82fd8e999fb4b9e829

here is the C++ test gist: https://gist.github.com/prigoyal/0a0ad421d50f31ad8a37ef0f9d0dc150

this was posted by our user in slack channel cc @moskomule

**Comment by nicolasvasilache** [comment]
So the gdb stack shows that the main thread is waiting, I bet your machine has 2 GPUs and the run seems stuck on GPU execution.
Given the nature of the problem (10-D loop with high flop count) it is not unreasonable that it takes so long given the way the TC is currently written.
But it's not a race condition which is always good news :)
