### ISSUE TITLE
Can't compile max reduction

### ISSUE THREAD

**Issue by arogozhnikov** [facebookresearch/TensorComprehensions#117]
When submitting a bug report, please include the following information (where relevant):
- OS: ubuntu 16.04
- How you installed TC (docker, conda, source): conda
- Python version: 3.6
- CUDA/cuDNN version: 9 / 7
- Conda version (if using conda): conda 4.3.30
- Docker image (if using docker): nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04
- GCC/GXX version (if compiling from source): 5.4.0
- LLVM/Tapir git hash used (if compiling from source): NA
- Commit hash of our repo and submodules (if compiling from source): NA

---

Hi, I'm  experimenting and in particular I try to implement convolutional part of lenet as a single function in TC. However max-pooling doesn't work for me 

Here is the script:

```python
lang = """
def lenet_convpart(float(B, 32, 32) I0, 
                   float(6, 5, 5) Weight1, float(6) Bias1) -> (O1, O2) {

    O1(b, c, h, w) +=! I0(b, h + kh, w + kw) * Weight1(c, kh, kw)
    O1(b, c, h, w) = fmax(0, O1(b, c, h, w) + Bias1(c))
    # trivial reduction not working
    O2(b, c, h, w) max=! O1(b, c, h, w)
    # this one is of actual interest
    # O2(b, c, h1, w1) max=! O1(b, c, h1 * 2 + kh1, w1 * 2 + kw1) where kh1 in 0:2, kw1 in 0:2
}
"""
N = 100
tensordot = tc.define(lang, name="lenet_convpart")
I0 = torch.randn(100, 32, 32).cuda()
W1 = torch.randn(6, 5, 5).cuda()
B1 = torch.randn(6).cuda()

best_options = tensordot.autotune(I0, W1, B1, cache=True)
out = tensordot(I0, W1, B1, options=best_options)
```

Here is the output:
```
[INFO]: Autotuning cache will be saved to: /tmp/lenet_convpart_100_32_32_6_5_5_6_53fe0682-3df7-42ae-9592-f279767ec145.cuda/options
[WARNING]: Using 'naive' type mapping options for autotuning. See help(your_layer.autotune) for how to set mapping options.
[ERROR]: Caught Exception: Could not compile function
```

**Comment by prigoyal** [comment]
Hi @arogozhnikov this was recently fixed a few minutes ago, I'll refresh the binaries soon and the reduction should work then. I'll post update on this task when it's done. Thanks :)

**Comment by arogozhnikov** [comment]
Wow, very quick. Just in case, is this the same problem below? It just crushes python kernel

```python
lang = '''
def avgpool(float(B, C, H, W) input) -> (output) {{
    output(b, c, h, w) += input(b, c, h * {sH} + kh, w * {sW} + kw) where kh in 0:{kH}, kw in 0:{kW}
}}
'''.format(sH=2, sW=2, kH=2, kW=2)


print(lang)

N = 100
tensordot = tc.define(lang, name="lenet_convpart")
I0 = torch.randn(100, 10, 32, 32).cuda()

best_options = tensordot.autotune(I0, cache=True)
out = tensordot(I0, options=best_options)
```

**Comment by prigoyal** [comment]
@arogozhnikov this example should be fine. We have test case for avgpool as well https://github.com/facebookresearch/TensorComprehensions/blob/master/test_python/layers/test_avgpool_autotune.py

does it simply crash with no error message?

**Comment by arogozhnikov** [comment]
This was the reason for the second example

> def avgpool
> name="lenet_convpart"

As I'm using jupyter, there is no output in notebook, but when I run it as a separate script, I found the problem.
```
[INFO]: Autotuning cache will be saved to: /tmp/lenet_convpart_100_10_32_32_32e8cd91-4064-44fd-b36b-fc8110813aad.cuda/options
[WARNING]: Using 'naive' type mapping options for autotuning. See help(your_layer.autotune) for how to set mapping options.
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0307 14:48:25.724678   423 execution_engine.cc:192] Check failed: tcNameMap_.count(name) == 1 (0 vs. 1) TC function lenet_convpart not defined
*** Check failure stack trace: ***
Aborted (core dumped)
```

**Comment by ftynse** [comment]
that should be turned into a compilation error instead of an assertion, thanks for pointing out

**Comment by ftynse** [comment]
tag #115 for `max=!` problem

**Comment by prigoyal** [comment]
@arogozhnikov yep, the name has to be the same and @ftynse is right that we should have this as compilation error and not assertion. we will look into fixing that in a separate issue.

**Comment by prigoyal** [comment]
the packages are up-to-date. @arogozhnikov you can do a `fresh` conda install of package and the max reduction should work fine now. let me know if it doesn't. here is our example test case https://github.com/facebookresearch/TensorComprehensions/blob/master/test_python/layers/test_softmax.py which works fine with max reduction

**Comment by arogozhnikov** [comment]
I confirm that provided example works now.

**Comment by prigoyal** [comment]
great to hear @arogozhnikov
