### ISSUE TITLE
[Build] ScheduleTree struct error schedule_tree.h

### ISSUE THREAD

**Issue by cbalint13** [facebookresearch/TensorComprehensions#119]
- OS: Fedora 28
- Python version: 3.6
- CUDA: 9.1
- GCC: 8.0.1

Hi Folks,

I am trying to pack TC as rpm package on RedHat/Fedora platform but have issues within **tc_executor.cc** & **schedule_tree.h** . Not sure what would be right declartion.

* In short:
```
polyhedral/schedule_tree.h:141:44: error: ‘std::ostream& tc::polyhedral::detail::operator<<(std::ostream&, tc::polyhedral::detail::ScheduleTree&)’ should have been declared inside ‘tc::polyhedral::detail’
```

* In details
```
/usr/bin/c++  -DCAFFE2_USE_GOOGLE_GLOG -DDMLC_USE_GLOG -Dtc_core_EXPORTS -I/home/cbalint/rpmbuild/BUILD/TensorComprehensions/src/../include -I/home/cbalint/rpmbuild/BUILD/TensorComprehensions/src/. -I/usr/lib/python2.7/site-packages/torch/lib/include -I/home/cbalint/rpmbuild/BUILD/TensorComprehensions/third-party/caffe2/third_party/eigen -I/usr/include/cuda -I/usr/include/cuda/include -I/home/cbalint/rpmbuild/BUILD/TensorComprehensions/third-party/dlpack/include -I/home/cbalint/rpmbuild/BUILD/TensorComprehensions/third-party/islpp/include -I/home/cbalint/rpmbuild/BUILD/TensorComprehensions/include -I/home/cbalint/rpmbuild/BUILD/TensorComprehensions/src/version -I/home/cbalint/rpmbuild/BUILD/TensorComprehensions/build/src/proto  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -mcet -fcf-protection -DCUDA_HOME="\"/usr/include/cuda\"" -DCUB_HOME="\"/usr/include\""  -Wall -Wno-sign-compare -fPIC  -o CMakeFiles/tc_core.dir/tc_executor.cc.o -c /home/cbalint/rpmbuild/BUILD/TensorComprehensions/src/core/tc_executor.cc -std=gnu++11
In file included from /home/cbalint/rpmbuild/BUILD/TensorComprehensions/src/../include/tc/core/halide2isl.h:25,
                 from /home/cbalint/rpmbuild/BUILD/TensorComprehensions/src/../include/tc/core/polyhedral/scop.h:27,
                 from /home/cbalint/rpmbuild/BUILD/TensorComprehensions/src/../include/tc/core/tc_executor.h:20,
                 from /home/cbalint/rpmbuild/BUILD/TensorComprehensions/src/core/tc_executor.cc:16:
/home/cbalint/rpmbuild/BUILD/TensorComprehensions/src/../include/tc/core/polyhedral/schedule_tree.h:141:44: error: ‘std::ostream& tc::polyhedral::detail::operator<<(std::ostream&, tc::polyhedral::detail::ScheduleTree&)’ should have been declared inside ‘tc::polyhedral::detail’
       tc::polyhedral::detail::ScheduleTree&);
```

**Comment by prigoyal** [comment]
@ftynse does this look familiar at all?

**Comment by ftynse** [comment]
No, we had other compilation problems with unsupported versions of GCC (>5.4), including problems in third-party dependences.

@cbalint13  note that CUDA does not support GCC>6.3 and you will likely run into further compilation

**Comment by ftynse** [comment]
The error message is misleading... Try moving the declaration of operator from line 513 to line 137 in `schedule_tree.h`.  I see other compilation problems due to CUDA/GCC incompatibilities.

**Comment by prigoyal** [comment]
@cbalint13 we officially support gcc 5.4 and below for TC and like @ftynse mentioned, there will be other issue with build for higher gcc version. Do you have a strict requirement for gcc 8 or are you fine using gcc5.4?

**Comment by cbalint13** [comment]
@prigoyal @ftynse 

* As @ftynse recommended i used gcc53 strict for the very TC build. Yes now it builds. Other dependencies like llvm-tapir can stay on gcc8. However I use nvcc with gcc53 so gcc53 is always present in the enviroment.

*  I tried to pack TC (among caffe2, pytorch and others) using fedora28 standard compiler gcc ver 8. Usually distros (including fedora) always come with older "compat" libriaries so gcc8 is not strict a requirement.


Thank you all for the feedback !

**Comment by cbalint13** [comment]
@ftynse ,

 * Just to pushed the limits toward gcc8 and moved declaration 513 -> 137. TC now pass the compile with gcc8 ! However CUDA's nvcc still remains invoked with -ccbin=/usr/bin/gcc53 (there is no other way).

**Comment by ftynse** [comment]
> Just to pushed the limits toward gcc8 and moved declaration 513 -> 137. TC now pass the compile with gcc8 ! However CUDA's nvcc still remains invoked with -ccbin=/usr/bin/gcc53 (there is no other way).

Great!  Do you mind submitting a patch with that change?  I can do it myself if you prefer.

**Comment by cbalint13** [comment]
@ftynse ,

Yes i can do it.
