### ISSUE TITLE
Problem in Importing tensor_comprehensions `[Installation]`

### ISSUE THREAD

**Issue by amirid** [facebookresearch/TensorComprehensions#126]
Hi,

Once I installed the TensorComprehensions in conda enviroment and the installation was successful, but I couldn't import the tensor_comprehensions:

`ImportError: No module named 'tensor_comprehensions'`

Then I installed the package from source, but again I encounter the mentioned error. I tried to run it with both python 2 and python3.

**Comment by prigoyal** [comment]
Hi amirid, can you tell me your environment config:

1. did you make a new conda env? or are you installing in root env?
2. does `import torch` work?
3. can you tell me the output of `which python`?

**Comment by amirid** [comment]
@prigoyal 
1. No I didn't create a new conda env, I installed it in base env.
2. Yes.
3. /usr/bin/python (I removed the anaconda when I decided to install tensor comprehensions from source, but when conda was installed the python path was ~/miniconda/bin)

**Comment by prigoyal** [comment]
2. what does `print(torch)` gives after you import torch?
3. yeah, so your python is not the conda python and the package was installed in conda root env

can you try:
```
conda create -y --name tc-env python=3.6
source activate tc-env
conda install -y -c pytorch -c tensorcomp tensor_comprehensions
```
and then try the import?

**Comment by amirid** [comment]
2. <module 'torch' from '/usr/local/lib/python3.5/dist-packages/torch/__init__.py'>
3.  Thank you, now it works :D

**Comment by prigoyal** [comment]
great, I'll close out this issue. thanks for confirming :)

**Comment by pranerd** [comment]
@prigoyal  did tensor comprehensions didn't support python2.7? I install it with anaconda2 environment, after that, try to import tensor_comprehensions, but it didn't work.
