### ISSUE TITLE
Vanilla LLVM support

### ISSUE THREAD

**Issue by nicolasvasilache** [facebookresearch/TensorComprehensions#128]
Would be nice if TensorComprehensions ran with non-Tapir LLVM.
Assigning tentatively to @wsmoses for now.

**Comment by prigoyal** [comment]
I thought it does now already, we don't really have strong dependence on Tapir-LLVM.

**Comment by salexspb** [comment]
src/core/polyhedral/codegen_llvm.cc:33:10: fatal error: 'llvm/Transforms/Tapir/CilkABI.h' file not found

**Comment by salexspb** [comment]
What is an ETA here? It is currently a blocking issue for us.

**Comment by ftynse** [comment]
Fixed in #139
