### ISSUE TITLE
[Build] Using protobuf installation at non-standard location

### ISSUE THREAD

**Issue by singam-sanjay** [facebookresearch/TensorComprehensions#133]
I want to use a protobuf installation within $HOME to build with TC. CMake picks up the path to the `protoc` application but seems to fail at picking the right include directories,
```
In file included from /home/sanjay/Projects/TensorComprehensions/build/src/proto/compcache.pb.cc:5:0:
/home/sanjay/Projects/TensorComprehensions/build/src/proto/compcache.pb.h:9:42: fatal error: google/protobuf/stubs/common.h: No such file or directory
compilation terminated.
In file included from /home/sanjay/Projects/TensorComprehensions/build/src/proto/mapping_options.pb.cc:5:0:
/home/sanjay//Projects/TensorComprehensions/build/src/proto/mapping_options.pb.h:9:42: fatal error: google/protobuf/stubs/common.h: No such file or directory
compilation terminated.
src/proto/CMakeFiles/tc_proto.dir/build.make:110: recipe for target 'src/proto/CMakeFiles/tc_proto.dir/compcache.pb.cc.o' failed
make[2]: *** [src/proto/CMakeFiles/tc_proto.dir/compcache.pb.cc.o] Error 1
```

with tc_proto.dir/build.make having the line,
```
cd /home/sanjay/Projects/TensorComprehensions/build/src/proto && /home/sanjay/Projects/proto-install/protobuf-3.4.0/install/bin/protoc --cpp_out cd /home/sanjay/Projects/TensorComprehensions/build/src/proto && /home/sanjay/Projects/proto-install/protobuf-3.4.0/install/bin/protoc --cpp_out /home/sanjay/Projects/TensorComprehensions/build/src/proto -I /home/sanjay/Projects/TensorComprehensions/src/proto /home/sanjay/Projects/TensorComprehensions/src/proto/compcache.protoProjects/TensorComprehensions/build/src/proto -I /home/sanjay/Projects/TensorComprehensions/src/proto /home/sanjay/Projects/TensorComprehensions/src/proto/compcache.proto
```

What can I do to ensure that the requisite include paths are included ?

Setup:
- OS: Ubuntu 16.04
- How you installed TC (docker, conda, source): build from source within a conda environment
- Python version: 3.6
- CUDA/cuDNN version: CUDA 8
- Conda version (if using conda): 4.4.11
- Docker image (if using docker):
- GCC/GXX version (if compiling from source): 5.4
- LLVM/Tapir git hash used (if compiling from source): 5.0.0git-195a877
- Commit hash of our repo and submodules (if compiling from source): recursively clone from 8c345a5cf967c9190b362f377e2152d4211cd980 of TC.

**Comment by prigoyal** [comment]
Hi @singam-sanjay how did you install protobuf?

**Comment by singam-sanjay** [comment]
Hi @prigoyal ,

I followed Step 6 of https://facebookresearch.github.io/TensorComprehensions/installation_conda.html with the following modifications,
1. `./configure --prefix=$PROTOBUF_DIR/install --exec_prefic=$PROTOBUF_DIR/install` intead of just `./configure`
2. Added the path to the protobuf shared lib files to LD_LIBRARY_PATH instead of executing ldconfig, since I don't have admin permissions.

**Comment by ftynse** [comment]
Did you change `CPATH` as well?

**Comment by singam-sanjay** [comment]
Setting CPATH to $PROTO_DIR:$CPATH solved the problem ! Thanks @ftynse

**Comment by jiaozizhao** [comment]
> $PROTO_DIR:$CPATH

Hi, I have the same issue with you. What do you mean change CPATH? Specifically how to solve the issue? Could you give me details, please? Thanks

**Comment by singam-sanjay** [comment]
@jiaozizhao CPATH was a variable used in the "./configure" script. I'm not sure if your issue is stemming from the same place since I had this issue more than 2 years ago.

**Comment by EndUser26** [comment]
What are you talking about ?

Sent💫

On Nov 20, 2020, at 12:40 AM, Singapuram Sanjay Srivallabh <notifications@github.com> wrote:

﻿

@jiaozizhao<https://github.com/jiaozizhao> CPATH was a variable used in the "./configure" script. I'm not sure if your issue is stemming from the same place since I had this issue more than 2 years ago.
