### ISSUE TITLE
Comparison operators

### ISSUE THREAD

**Issue by abadams** [facebookresearch/TensorComprehensions#16]
The front-end doesn't understand ==, <, >, !=, etc. Hilariously, we *do* have a ternary operator, but I'm not sure what you would use for the first argument :)

Tagging @zdevito to add them to the lexer/parser

**Comment by abadams** [comment]
I got lost somewhere inside semantic checking and type inference with this. I think this will be trivial for Zach, so I'll leave it to him.

**Comment by prigoyal** [comment]
done in #28
