### ISSUE TITLE
Bug of returned data type - Variable instead of Tensor

### ISSUE THREAD

**Issue by leftthomas** [facebookresearch/TensorComprehensions#170]
- OS: Linux64
- How you installed TC (docker, conda, source): conda
- Python version: Python3.6.4
- CUDA/cuDNN version: CUDA8.0/cuDNN7.0.5
- Conda version (if using conda): 4.4.11

I have written an example to test matmul, and I found if I use PyTorch Tensor to compute, then the TC will return a Variable, but not Tensor, I think TC should return Tensor when we call it through Tensor, return Variable when we call it through Variable. By the way, I found TC is similar with [CuPy](https://github.com/cupy/cupy).
<img width="1050" alt="qq20180319-212405 2x" src="https://user-images.githubusercontent.com/9991443/37597972-e0012eba-2bbb-11e8-836b-fa2f7df07f67.png">

**Comment by prigoyal** [comment]
thanks @leftthomas , indeed this is an oversight. we'll fix this and update will be released in next binaries. Thanks for reporting :)

**Comment by leftthomas** [comment]
@prigoyal There are a doc typo bug of `tc.options` about `group conv`, the desc of `conv` is same to `group conv`. 
<img width="1027" alt="qq20180320-110155 2x" src="https://user-images.githubusercontent.com/9991443/37633738-7e551578-2c2e-11e8-972f-bd2b57bbbb3d.png">

**Comment by prigoyal** [comment]
this will be addressed in the next TC release where Variable/Tensor will be merged as per PyTorch changes. Closing this task in favor of #199 where this point has been added. :) thanks a lot.
