### ISSUE TITLE
Bug of doc example

### ISSUE THREAD

**Issue by leftthomas** [facebookresearch/TensorComprehensions#176]
- OS: Linux64
- How you installed TC (docker, conda, source): conda
- Python version: Python3.6.4
- CUDA/cuDNN version: CUDA8.0/cuDNN7.0.5
- Conda version (if using conda): 4.4.11

1. There are a doc typo bug of `tc.options` about `group conv`, the desc of `conv` is same to `group conv`. 
<img width="1027" alt="qq20180320-110155 2x" src="https://user-images.githubusercontent.com/9991443/37633738-7e551578-2c2e-11e8-972f-bd2b57bbbb3d.png">

2. There are a doc typo bug of `avgpool` example, the `avgpool` is not sum op. 
<img width="1185" alt="qq20180320-142650 2x" src="https://user-images.githubusercontent.com/9991443/37639022-c11a6cfc-2c4a-11e8-8025-8b14ed44dd99.png">

3. There are a doc typo bug of `maxpool` example, the `max=` should be `max=!`, or it will got wrong answer if the image size not divided by the kernel size. 
<img width="1239" alt="qq20180320-165027 2x" src="https://user-images.githubusercontent.com/9991443/37644529-16534a72-2c5f-11e8-845e-7f27be7bad20.png">

By the way, I think the doc is obscure to understand.

**Comment by prigoyal** [comment]
thanks @leftthomas for the report. This will be fixed in the next release cycle :)
