### ISSUE TITLE
How to define padding in convolution layer

### ISSUE THREAD

**Issue by merrymercy** [facebookresearch/TensorComprehensions#186]
In ML layer database (https://facebookresearch.github.io/TensorComprehensions/framework/pytorch_integration/layers_database.html#convolution-layers), I cannot find examples about padding.
How to express that in TC?

**Comment by prigoyal** [comment]
Hi @merrymercy , we don't explicitly support padding in TC yet. There is task open for it already, #11

**Comment by prigoyal** [comment]
I'll close out this as duplicate issue now.
