### ISSUE TITLE
Problem with range inference

### ISSUE THREAD

**Issue by stemill** [facebookresearch/TensorComprehensions#191]
- OS: Ubuntu 16.04
- How you installed TC: conda
- Python version: 3.6
- CUDA/cuDNN version: 9.1/7.1
- Conda version (if using conda): 4.4.10

There appears to be a problem with range inference. In the example below I expected the output tensor to have shape [5,2], not [5, 5]

```python
import tensor_comprehensions as tc
import torch
import numpy as np

LANG = """
def testcomp(float(I) B) -> (A) {
  A(i, j) = B(i) + B(j+3)
}
"""
testcomp = tc.define(LANG, name="testcomp")
B = torch.Tensor(np.arange(5)).cuda()
out = testcomp(B)
out

Variable containing:
 3  4  1  2  3
 4  5  2  3  4
 5  6  3  4  5
 6  7  4  5  6
 7  8  0  0  0
```

**Comment by prigoyal** [comment]
thanks @stemill , this issue is duplicate to #12 , I'll close out this in in favor of that. :)
