### ISSUE TITLE
Increase the default number of the autotuner generations in python bindings.

### ISSUE THREAD

**Issue by ftynse** [facebookresearch/TensorComprehensions#195]
https://github.com/facebookresearch/TensorComprehensions/blob/479815449a3a438a69ba21b8c2eb9bf52c594443/tensor_comprehensions/tc_unit.py#L192

By default, the autotuner in python runs 2 generations with very small population size.  This is largely insufficient, even "some check" tests run longer.

@prigoyal @nicolasvasilache @ttheodor 

- [x] bump up the defaults in tc_unit.py 
- [x] modify python unit tests to still use old settings to have faster CI testing

**Comment by ttheodor** [comment]
This doesn't make sense at all. It should definitely be bumped up.

**Comment by prigoyal** [comment]
Hi all, thanks for the discussion. What settings would you like to have for these options? concrete numbers would help.

cc @soumith @hmansell

**Comment by prigoyal** [comment]
assigning to @ftynse and @ttheodor for providing some concrete numbers on the settings. I can make the required changes then. Thank you :)

**Comment by ftynse** [comment]
I would recommend a benchmark-centered approach.  We run tuning on scale once and analyze after how many generations the performance increases only at a small rate, and pick that value.

However, I am unable to run tuning on scale and neither is @ttheodor AFAIK.

**Comment by prigoyal** [comment]
that sounds reasonable. assigning to Nicolas as well for providing some stats. :)

**Comment by fsword73** [comment]
During the evaluation of SGEMM,  MNK from 128 to 4096.  The best performance is only 18% of Peakflops.   Most SGEMM's performance is less than 5% PeakFlops.  

It will be great with big polulation size and generations.  

A demo autotuner of SGEMM with effective 80% Peak Flops will bring out real confidence to encourage developer to integrate TC as backend.  Or Even demo tuning process of SGEMM will be execellent enough

**Comment by ftynse** [comment]
@fsword73 

Performance of sgemm is not likely to increase significantly however long you run the TC autotuner.

We need to perform several other code transformations than we currently do to speed up gemm more. Note that gemm is the most hand-optimized kernel in history.  For the vast majority of sizes, library versions do a good job on it.  So if your library version runs fast, you are better off just using it.  In fact, we are going to match library calls instead of generating code whenever we deem this more efficient.  We believe it should not stop framework integration of TC.  One does not have to express _all_ layers in TC, especially not those where achieved performance is already good enough.

**Comment by prigoyal** [comment]
very exciting to hear about the library call matching. @ftynse , I was curious if we have heuristics or ideas around how to detect whether a kernel for some sizes will be more efficient in a library or TC should do codegen. Do we have thoughts on that? :) Thanks.

**Comment by nicolasvasilache** [comment]
@prigoyal it shouldn't be a surprise, we've been discussing this for a few months already :) Reg. implementation of the decision, a prereq is to have proper modeling and a roofline estimate. #198 is a first step in that direction.

**Comment by prigoyal** [comment]
thanks @nicolasvasilache, definitely not a surprise to me :) I am rather curious about the details/ideas there and if this is happening anytime soon. Thanks for pointer to #198. I will wait out for a roadmap to be available likely for more information :) thanks again.

**Comment by nicolasvasilache** [comment]
Reg. default sizes, ```pop_size=20, crossover_rate=80, mutation_rate=7, generations=10``` should be a good tradeoff between coverage and speed for users that do not want to look into the details.
We could also bump to ```generations=20``` if we don't get too many complaints.

Sounds reasonable @ttheodor ?

**Comment by prigoyal** [comment]
It looks like we are reaching over consensus here. I will assign it to myself now to make the requested changes. Thanks everyone for discussion. :)

**Comment by ttheodor** [comment]
My feeling is that we should bump the population size more, but probably my feeling is as good as anyone's. Having said that, with  `pop_size=20,  generations=10`, we are exploring at most 200 variants. We have at least ~10 tunable parameters per kernel (and if we include tile/block/sizes, then more), I have very little confidence that there will be any reasonable exploration of that search space with only 200 candidates. 

In addition there are extra parameters introduced in #160 (that affect runtime) for which we need to choose "reasonable" defaults.

**Comment by prigoyal** [comment]
thanks @ttheodor , can you provide me with the numbers for the parameters that we should set? Happy to have that change :)

**Comment by fsword73** [comment]
@ftynse .  Calling of vendeor  GEMM is good choice since GEMM is mostly manual optmized.  
AMD has  "https://github.com/ROCmSoftwarePlatform/Tensile which optimizes GEMM and batched GEMM by Auto-tuning.  GEMM is the basic test to have confidence from Developer.  In other words,  Is there any guidelines to integerate other backend like AMD ROCm.  Tensile will be good backend baseline to support Tensor operatation.

**Comment by ftynse** [comment]
Do you mind opening a separate issue for this discussion? It is completely
orthogonal to the autotuning.
