### ISSUE TITLE
untangle compilation/tuning/options relation in the documentation

### ISSUE THREAD

**Issue by ftynse** [facebookresearch/TensorComprehensions#196]
Documentation, in particular the [tutorial](https://facebookresearch.github.io/TensorComprehensions/tutorials/tutorial_tensordot_with_tc.html), sort of hides the relation between compilation and tuning.  This has led to many misconceptions about how TC actually works:
- compilation != autotuning, the latter runs the former thousands of times
- compilation errors mean incorrect syntax and the TC expression should be fixed, errors in autotuning mean internal failures and should be reported (but do not necessarily break the further execution)
- mapping options passed to the autotuner are only a starting point in the search space, unlike those passed to compilation
- autotuning is non-deterministic by nature, different runs produce different results _independently_ of the starting point.

**Comment by ftynse** [comment]
cc @prigoyal

**Comment by prigoyal** [comment]
thanks @ftynse, great point. Would you like to take a stab at correcting the docs to make things more verbose and clear since you have been seeing these misconceptions from users? :) assigning to you tentatively.

**Comment by ftynse** [comment]
tutorial is dead
