### ISSUE TITLE
Compilation Cache keys

### ISSUE THREAD

**Issue by ttheodor** [facebookresearch/TensorComprehensions#205]
Part of the compilation cache keys is a TC's ID. Up until now we have been using the function name of a TC. As it has been discussed multiple times we want to switch to something more discriminative.   

One idea that has been floating is to use a pretty printed version of the whole TC definition. Are there are any other suggestions/alternatives?

**Comment by nicolasvasilache** [comment]
@zdevito created an anomization function for  TC before the release. Iirc
there is 1 test so look up in the tests to find it ? I can point you to it
tomorrow otherwise
