### ISSUE TITLE
porting the examples in python using the provided python binding

### ISSUE THREAD

**Issue by mscipio** [facebookresearch/TensorComprehensions#22]
As in the title, do you have any plan to provide working example of the currently available python binding interface, or will you just wait to release them with PyTorch bindings?

**Comment by prigoyal** [comment]
Hi @mscipio, thank you for the query. We will provide the python examples as part of PyTorch bindings. They will be made available in few weeks.

**Comment by PatWie** [comment]
It it currently possible or not?

```python

import torch
import torch.utils.dlpack
from autotuner import ATenAutotuner
from mapping_options import Options

opt = Options("naive")
opt.useSharedMemory(True)

src = """def matmul(float(M,N) A, float(N,K) B) -> (output) {
    output(i, j) +=! A(i, kk) * B(kk, j)
}
"""

tuner = ATenAutotuner(src)
ATenAutotuner.gpus(tuner, "1")

inputs = [torch.FloatTensor(30, 40).zero_().cuda(),
          torch.FloatTensor(40, 50).zero_().cuda()]

ATenAutotuner.tune(tuner, "", "matmul", inputs, opt, [opt])
```

gives me

```
W0222 19:04:59.388272  3350 rtc.cc:103] Compilation failure for nvrtc(NVRTC_ERROR unknown): 
nvrtc: error: failed to load builtins source:
```

**Comment by prigoyal** [comment]
Hi @PatWie we don't have any python tests running via autotuner atm and hence you might run into errors like above. We recommend waiting out for our official support for PyTorch. Thanks!

**Comment by prigoyal** [comment]
We have python bindings ready and we will shortly provide the python bindings and the documentation for using them. Closing this issue :)
