### ISSUE TITLE
Correct way to use integer tensors with pytorch?

### ISSUE THREAD

**Issue by arogozhnikov** [facebookresearch/TensorComprehensions#224]
When submitting a bug report, please include the following information (where relevant):
- OS: ubuntu 16.04
- How you installed TC (docker, conda, source): conda
- Python version: 3.6
- CUDA/cuDNN version: 9 / 7
- Conda version (if using conda): conda 4.3.30
- Docker image (if using docker): nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04
- GCC/GXX version (if compiling from source): NA
- LLVM/Tapir git hash used (if compiling from source): NA
- Commit hash of our repo and submodules (if compiling from source): NA
---

So far I wasn't able to pass integer tensors. Initially followed an example from docs with stride shifts. Simplified that example, but still no success

Tried:
```python
import tensor_comprehensions as tc
import torch

lang = """
def my_op(int(I) x) -> (output) {
  output(i) +=! x(i)
}
"""
fcrelu = tc.define(lang, name="my_op")
x = torch.arange(20).int()
out = fcrelu(x)
```

Also tried:
```python
lang = """
def my_op(int32(I) x) -> (output) {
  output(i) +=! x(i)
}
```

And 
```python
lang = """
def my_op(uint32(I) x) -> (output) {
  output(i) +=! x(i)
}
```
in the last case I don't know how to create uint32 tensor in pytorch.

**Comment by prigoyal** [comment]
Hi @arogozhnikov , 
```
lang = """
def my_op(int32(I) x) -> (output) {
  output(i) +=! x(i)
}
```
this seems like the right way. we support `int32` . Can you report what error you are getting and we can certainly look further? :)

**Comment by arogozhnikov** [comment]
Here is what I get:
```bash
# cat tc_example1.py
import tensor_comprehensions as tc
import torch

lang = """
def my_op(int32(I) x) -> (output) {
  output +=! x(i)
}
"""
fcrelu = tc.define(lang, name="my_op", )
x = torch.arange(20).int()
out = fcrelu(x)(py36) 
```


```bash
# python tc_example1.py
[WARNING]: No mapping options passed, 'naive' type mapping options will be used and will likely have bad performance. See help(your_layer.__call__) for setting mapping options.
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0327 15:09:52.504698  2484 rtc.cc:144] Error at: /opt/conda/conda-bld/tensor_comprehensions_1520457708651/work/src/core/rtc.cc:144: CUDA_ERROR_INVALID_CONTEXT
[ERROR]: Caught Exception: Error at: /opt/conda/conda-bld/tensor_comprehensions_1520457708651/work/src/core/rtc.cc:144: CUDA_ERROR_INVALID_CONTEXT
W0327 15:09:52.512689  2484 rtc.cc:44] Error at: /opt/conda/conda-bld/tensor_comprehensions_1520457708651/work/src/core/rtc.cc:44: CUDA_ERROR_INVALID_HANDLE
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error at: /opt/conda/conda-bld/tensor_comprehensions_1520457708651/work/src/core/rtc.cc:44: CUDA_ERROR_INVALID_HANDLE
Aborted (core dumped)
```

Any additional info needed?

**Comment by prigoyal** [comment]
thanks @arogozhnikov, from the first look, it seems that the tensor is not a `cuda` tensor. may I recommend that you try it out by creating the cuda tensor x. You can also find one example of passing int32 tensors here https://github.com/facebookresearch/TensorComprehensions/blob/0d34ee36b757079e89058218a9186ae2a1f3b600/test_python/layers/test_indexing.py#L28 :)

**Comment by arogozhnikov** [comment]
> from the first look, it seems that the tensor is not a cuda tensor

Yes, sorry, I forgot about this again.

Thanks for pointing, I think that this example
```python
def subsample_2(float(I) B, int(1) S) -> A {
``` 
should be fixed, because in my case just `int` didn't work., only `int32`

**Comment by prigoyal** [comment]
makes sense, we'll fix that. Thanks @arogozhnikov :)
