### ISSUE TITLE
Expose the setting for saving # best candidates in autotuning

### ISSUE THREAD

**Issue by prigoyal** [facebookresearch/TensorComprehensions#243]
Currently, by default, we save 10 best candidates in autotuning and number `10` is also hardcoded here https://github.com/facebookresearch/TensorComprehensions/blob/master/src/autotuner/genetic_autotuner.cc#L60

Recently, some friendly users have asked if it is possible to rather set the number of candidates or maybe even save all i.e. can we expose this setting to users?

IMO, this seems like a legit change but I would like to hear views from @ttheodor if we should do this or not.  The change is quite simple. Set the gflag for it with default value 10 and then expose this flag to the pybind as well.

cc @sidelnik

**Comment by prigoyal** [comment]
Hi @ttheodor , I would love to hear your views on this particular case. Thanks :)

**Comment by ttheodor** [comment]
The only reason we are not saving more is space. We can definitely expose this option.

**Comment by prigoyal** [comment]
cool, I'll make this change and send it out for your review. :) thanks @ttheodor
