### ISSUE TITLE
Autotuner questions and feedback

### ISSUE THREAD

**Issue by prigoyal** [facebookresearch/TensorComprehensions#287]
one of our users @jzbontar was using TC autotuner and had the following feedback/questions. I am creating this issue to get more eyes and thoughts from @ttheodor who's our autotuner master :) 

1. When profiling a kernel, does the autotuner call it more than once (for example, to get an accurate measurement)? If yes, then consider making the number of times a kernel is called depend on the kernel’s execution time. Kernels that take a long time to run should not be executed many times. 

2. Can we terminate trials that take longer than, say, 3 * time_of_best_run? Is this already done currently? 

3. When autotuner segfaults due to illegal memory access, it raises abort. It should rather throw exception. Can this be corrected? #271 
   
4. Ctrl-C
  When you hit Ctrl-C to stop the autotuner it does not stop immediately. Instead you have to wait until the end of the generation. This requires changes to the way thread management is implemented right now: i.e. a generation is spinned and if the SIGINT is raised then the current generation continues.

**Comment by prigoyal** [comment]
hey @ttheodor, can you take a look and help answer a few things in this issue? :) thanks a lot for your help.

**Comment by nicolasvasilache** [comment]
Hi @jzbontar, here are some answers:
1. for the purpose of the autotuner we currently run 3 warmup iterations and 10 benchmark iterations. We have a catastrophically bad threshold set to 100 to prune out the worst cases after the first run.
We have another early pruning check for versions that have too few threads (with --tuner_min_launch_total_threads) to avoid even that first run.
Worst cases will still be run once 
2. yes, we have that set to 5 atm
3. unfortunately no, this is a hard cuda limitation 
4. @ttheodor will know better for this one

**Comment by jzbontar** [comment]
Thanks @prigoyal for opening the issue and @nicolasvasilache for your answers.

3. I hope asking silly questions is okay here :) Are you running the genetic algorithm trials in a new thread or in a new process? If you run them in a new process, wouldn't that solve this problem, as only the newly created process would abort and the main process would continue running? Would that maybe break something else (for example, if someone has their gpu set to exclusive process mode)?

4. This has very low priority from my point of view.

**Comment by ftynse** [comment]
4. is a issue that caused long and painful discussions in python integration;  in some cases, aborting the tuning led to python shell being killed; @prigoyal should know this part very well :)

I still claim that running the entire autotuner in a separate process and killing off that process is a good idea.

**Comment by ttheodor** [comment]
Yes, 3. and 4. can be (partially) solved by running the tuner in a separate process. 

3. would be solved partially because the whole tuning session would be killed and not just the individual who caused the segfault, unless we run each individual in a separate process (but this might be a bit of an overkill).

**Comment by ftynse** [comment]
Ctrl+C behavior was corrected by #476.  Other questions have got answers, no further action possible. Closing.
