### ISSUE TITLE
[build]TC compile error from source code 

### ISSUE THREAD

**Issue by qzhong0605** [facebookresearch/TensorComprehensions#296]
- OS: CentOS-7.3.1611
- How you installed TC (docker, conda, source): source
- Python version: 2.7.5
- CUDA/cuDNN version: cudnn-6.0.21
- GCC/GXX version (if compiling from source): gcc-4.8.5(g++-4.8.5)
- LLVM/Tapir git hash used (if compiling from source):  clang(2637f015d66418964aa0225534c004dd71a174b8) LLVM(5c2fdbbfc263e76384b49a7183b12a6b7132873d)

- Commit hash of our repo and submodules (if compiling from source): 
 on master branch: 40d6b7dda6b1e5d0bcb865cc6bf463b5e545b3a0
 
 f234e94aedffdbd9a47092ac36ea1784da8bc50a third-party/ATen (remotes/origin/sync_test-25-gf234e94)
 5651c4ce0279c895cbb1d1eeecc6594cc8791103 third-party/caffe2 (v0.8.1-1126-g5651c4c)
 6218c3dfdbdc38a072be65afc0c9b4558ea749df third-party/cub (v1.7.4-3-g6218c3d)
 10892ac964f1af7c81aae145cd3fab78bbccd297 third-party/dlpack (v0.2)
 4663c80d3ab19fc7d9408fe8fb22b07b87c76e5a third-party/gflags (v2.2.1-1-g4663c80)
 d0531421fd5437ae3e5249106c6fc4247996e526 third-party/glog (v0.3.3-157-gd053142)
 69e48e92de43960a316a826293510b7b3deb9eca third-party/googletest (release-1.8.0-371-g69e48e9)
 fe85f6a70e9d2f16d5a1591b90c8e598dbcf4c7f third-party/halide (release_2013_11_11-802-gfe85f6a)
 d74282c81fb6566626cc77288f875b3cbb5491db third-party/islpp (isl-0.18-1504-gd74282c)
 86e2ad4f77442c3350f9a2476650da6bee253c52 third-party/pybind11 (v2.2.1)

In addition, including the following information will also be very helpful for us to diagnose the problem:
- A script to reproduce the issue (highly recommended if its a build issue)
   BUILD_TYPE=Debug PYTHON=$(which python) WITH_CAFFE2=OFF CLANG_PREFIX=PATH/thirdparty/llvm/ ./build.sh  --all

- Error messages and/or stack traces of the issue (create a gist)
[ 58%] Building CXX object tc/core/CMakeFiles/tc_cuda.dir/cuda/cuda_tc_executor.cc.o
[ 58%] Linking CXX executable test_inference
../tc/core/libtc_cored.so: undefined reference to `typeinfo for Halide::Internal::IRMutator2'
../tc/core/libtc_cored.so: undefined reference to `typeinfo for Halide::Internal::IRVisitor'
../tc/core/libtc_cored.so: undefined reference to `typeinfo for Halide::Internal::IRGraphVisitor'
../tc/core/libtc_cored.so: undefined reference to `typeinfo for Halide::Internal::IRPrinter'
collect2: error: ld returned 1 exit status
make[2]: *** [test/test_inference] Error 1
make[1]: *** [test/CMakeFiles/test_inference.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 59%] Linking CXX executable test_tc2halide
../tc/core/libtc_cored.so: undefined reference to `typeinfo for Halide::Internal::IRMutator2'
../tc/core/libtc_cored.so: undefined reference to `typeinfo for Halide::Internal::IRVisitor'
../tc/core/libtc_cored.so: undefined reference to `typeinfo for Halide::Internal::IRGraphVisitor'
../tc/core/libtc_cored.so: undefined reference to `typeinfo for Halide::Internal::IRPrinter'
collect2: error: ld returned 1 exit status
make[2]: *** [test/test_tc2halide] Error 1
make[1]: *** [test/CMakeFiles/test_tc2halide.dir/all] Error 2
[ 60%] Linking CXX executable test_core
../tc/core/libtc_cored.so: undefined reference to `typeinfo for Halide::Internal::IRMutator2'
../tc/core/libtc_cored.so: undefined reference to `typeinfo for Halide::Internal::IRVisitor'
../tc/core/libtc_cored.so: undefined reference to `typeinfo for Halide::Internal::IRGraphVisitor'
../tc/core/libtc_cored.so: undefined reference to `typeinfo for Halide::Internal::IRPrinter'
collect2: error: ld returned 1 exit status
make[2]: *** [test/test_core] Error 1
make[1]: *** [test/CMakeFiles/test_core.dir/all] Error 2
[ 61%] Linking CXX shared library libtc_core_cuda_no_sdkd.so
[ 61%] Linking CXX shared library libtc_cudad.so
[ 61%] Built target tc_core_cuda_no_sdk
[ 61%] Built target tc_cuda
[ 62%] Linking CXX shared library libtc_core_cpud.so
[ 62%] Built target tc_core_cpu
make: *** [all] Error 2

**Comment by qzhong0605** [comment]
I'm sorry. I forgot a `$` sign in the PATH environment variable.

So the followings are the output of the command `llvm-config --has-rtti` and `llvm-config --cxxflags`:

For command `llvm-config --has-rtti`:
     > llvm-config --has-rtti
       YES
For command `llvm-config --cxxflags`:
  > llvm-config --cxxflags
-I$LLVM_PREFIX/include  -fPIC -fvisibility-inlines-hidden -std=c++1y -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -ffunction-sections -fdata-sections -O2    -DLLVM_BUILD_GLOBAL_ISEL -D_GNU_SOURCE -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS

Maybe you want to be sure the `rtti` information whether be generated or not.  I had checked the `halide` shared library. The following result is the some output for `nm --demangle libHalide.so  | grep IRPrinter` command:

`0000000001ba94f0 T Halide::Internal::IRPrinter::do_indent()
0000000001ba7600 T Halide::Internal::IRPrinter::IRPrinter(std::ostream&)
0000000001ba7600 T Halide::Internal::IRPrinter::IRPrinter(std::ostream&)
0000000001ba69b0 T Halide::Internal::IRPrinter::~IRPrinter()
0000000001ba6990 T Halide::Internal::IRPrinter::~IRPrinter()
0000000001ba6990 T Halide::Internal::IRPrinter::~IRPrinter()
00000000073d0f20 V vtable for Halide::Internal::IRPrinter
`

**Comment by qzhong0605** [comment]
I had worked around the problem. The reason is that the `halide` is compiled with `no-rtti`, with lossing `typeinfo` . I recompile `halide` with 'rtti' and build `TC` successfully

**Comment by prigoyal** [comment]
@qzhong0605 , please feel free to close the issue if the build is working now. Thanks :)
