### ISSUE TITLE
ATen submodule points to non-existing commit

### ISSUE THREAD

**Issue by bartvm** [facebookresearch/TensorComprehensions#328]
Running `git clone https://github.com/facebookresearch/TensorComprehensions.git --recursive` gives
```
error: Server does not allow request for unadvertised object f234e94aedffdbd9a47092ac36ea1784da8bc50a
Fetched in submodule path 'third-party/ATen', but it did not contain f234e94aedffdbd9a47092ac36ea1784da8bc50a. Direct fetching of that commit failed.
```
and `git submodule update --init --recursive` gives
```
error: Server does not allow request for unadvertised object f234e94aedffdbd9a47092ac36ea1784da8bc50a
Fetched in submodule path 'third-party/ATen', but it did not contain f234e94aedffdbd9a47092ac36ea1784da8bc50a. Direct fetching of that commit failed.
```
It looks like the current submodule points to https://github.com/zdevito/aten/tree/f234e94aedffdbd9a47092ac36ea1784da8bc50a, but that commit has disappeared (rewrite/force push?). It seems like it was replaced with https://github.com/zdevito/ATen/tree/13d8a3f2d43ccd7d274b66b5f68372ccbd16de17, which doesn't compile since it looks for `CMakeLists.txt` which is no longer there...

I'm trying to compile now by checking out https://github.com/zdevito/aten/tree/old_master, but could someone confirm what the correct ATen commit to compile with is?

**Comment by skimo-openhub** [comment]
On Fri, Apr 20, 2018 at 01:33:33AM +0000, Bart van Merriënboer wrote:
> Running `git clone https://github.com/facebookresearch/TensorComprehensions.git --recursive` gives
> ```
> error: Server does not allow request for unadvertised object f234e94aedffdbd9a47092ac36ea1784da8bc50a
> Fetched in submodule path 'third-party/ATen', but it did not contain f234e94aedffdbd9a47092ac36ea1784da8bc50a. Direct fetching of that commit failed.
> ```
> and `git submodule update --init --recursive` gives
> ```
> error: Server does not allow request for unadvertised object f234e94aedffdbd9a47092ac36ea1784da8bc50a
> Fetched in submodule path 'third-party/ATen', but it did not contain f234e94aedffdbd9a47092ac36ea1784da8bc50a. Direct fetching of that commit failed.
> ```
> It looks like the current submodule points to https://github.com/zdevito/aten/tree/f234e94aedffdbd9a47092ac36ea1784da8bc50a, but that commit has disappeared (rewrite/force push?). It seems like it was replaced with https://github.com/zdevito/ATen/tree/13d8a3f2d43ccd7d274b66b5f68372ccbd16de17, which doesn't compile since it looks for `CMakeLists.txt` which is no longer there...
> 
> I'm trying to compile now by checking out https://github.com/zdevito/aten/tree/old_master, but could someone confirm what the correct ATen commit to compile with is?

I have no idea what happened.
It seems to have been completely rewritten!
I created #329, but caffe2 may have to undergo the same treatment.
I also happened to pick 92b2e07fff0b7744a4185597ab3c07e27b5a275f
instead of 13d8a3f2d43ccd7d274b66b5f68372ccbd16de17.
I have no idea what the difference is between them.

skimo

**Comment by prigoyal** [comment]
Hi @bartvm and @skimo-openhub  , thanks for the report. This is a known problem. I am working on fixing this actively today.

**Comment by skimo-openhub** [comment]
On Fri, Apr 20, 2018 at 03:09:40PM +0000, Priya Goyal wrote:
> Hi @bartvm and @skimo-openhub  , thanks for the report. This is a known problem. I am working on fixing this actively today. 

Nicolas already merged #329, but you can still do it properly
on top of that.

skimo

**Comment by gautamkmr** [comment]
Due to this, I am unable to clone the caffe2 repo
https://github.com/pytorch/pytorch/issues/6776

**Comment by skimo-openhub** [comment]
On Sat, Apr 21, 2018 at 11:57:56PM -0700, Gautam Kumar wrote:
> Due to this, I am unable to clone the caffe2 repo

Which one?  We temporarily switched to a different one until
the ATen issue in Caffe2 is solved.
Please open a different issue, because this one has been solved.

skimo

**Comment by skimo-openhub** [comment]
Closed by #329.

**Comment by gautamkmr** [comment]
How do I currently clone caffe2 repo?

**Comment by ftynse** [comment]
I guess you can ask caffe2 developers about that.  The [official page](https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile) provides some information.
