### ISSUE TITLE
Implement CHECK macros as exceptions

### ISSUE THREAD

**Issue by nicolasvasilache** [facebookresearch/TensorComprehensions#351]
At the moment we have too many places where we call one of the glog CHECK macros and terminate when it fails.
Let's implement our own CHECK macros and recover when it makes sense.
@salexspb @Yangqing I know C2 has its way of dealing with this, could you offer some guidance on what would make the most sense wrt FB infra?

Assigning to @ttheodor since we discussed about this last month.

**Comment by nicolasvasilache** [comment]
Related to [this](https://github.com/facebookresearch/TensorComprehensions/pull/327#discussion_r184203685).

**Comment by ftynse** [comment]
Related to #193
