### ISSUE TITLE
What's the input dimensions of relu operator?

### ISSUE THREAD

**Issue by QiJune** [facebookresearch/TensorComprehensions#416]
The relu example is following:
https://github.com/facebookresearch/TensorComprehensions/blob/9cc088fe034142199fd63717a2d59b15394b38c4/test_python/layers/test_relu.py#L25-L33

In this example, the input dimensions of relu is defined as 2. In fact, the input of relu can be any dimensions, like NCHW, a four dimensions Tensor. So a tensor reshape(or view) has to be done before. Otherwise it will cause error like:
```
[ERROR]: Caught Exception:
expected a tensor with 2 dimensions but found 1 dimensions
```

More generally, many element-wise operators, like exp/relu/add,  treat a Tensor just like a Vector. We can write relu tensor comprehensions just take a vector in, and a vector out. Just like:

```python
LANG = """
def relu(float(B) I) -> (O1){
  O1(b) = fmax(I(b), 0)
 }
"""
relu = tc.define(LANG, name="relu")
inp = torch.randn(4, 4, 4, 4).cuda()
in1 = inp.view(-1)
out = relu(in1)
```

But this will introduce a reshape(view) operation for every tc operator I wrote. It's a little inconvenient.
Is there any sugesstions? Thanks.

**Comment by nicolasvasilache** [comment]
@QiJune how about the following :) ?
```
def relu(float(N, C, H, W, Q, R, S, T) I) -> (O1){
  O1(n, c, h, w, q, r, s, t) = fmax(I(n, c, h, w, q, r, s, t), 0)
 }
```

In general many of the reshape / broadcast semantics and concat operations that people introduce in their layers are very artificial and come from the fact that one needs to map to an underlying library with far from ideal semantics.

I would claim with TC you should not worry about those most of the time. There are of course exceptions but relu seem simple enough that you don't want reshapes. 
If you are using your output outside of TC as an input to a library that expects a particular shape then definitely a reshape will be required there.

Does this make sense?

**Comment by QiJune** [comment]
@nicolasvasilache
In this example: 
```
def relu(float(N, C, H, W, Q, R, S, T) I) -> (O1){
  O1(n, c, h, w, q, r, s, t) = fmax(I(n, c, h, w, q, r, s, t), 0)
 }
```
If my input is a four dimensions Tensor, it seems that I can not use this relu function directly.
If I want to implement a VGG16 neural network with TC, then, I have to write all the TC operations myself?

Another question:
Maybe in network A, the input of relu is a two dimension Tensor; in network B, the input of relu is a four dimension Tensor. What should I do?

- implement relu twice or
- implement relu based on vector, and view the input tensor as a vector before call it

Thanks.

**Comment by nicolasvasilache** [comment]
> If my input is a four dimensions Tensor, it seems that I can not use this relu function directly.

No, you cannot, you would implement a 4-D version of this strawman function.

> If I want to implement a VGG16 neural network with TC, then, I have to write all the TC operations myself?

TC is meant to be used as a CUDA kernel generator, not for writing networks at this stage.
For VGG16 I would use a framework with CuDNN integration, benchmark and if I saw poor performance on certain kernels I would try TC on them. Note that TC is not meant to be used to optimize large matrix multiplications and convolutions at the moment (just use CuDNN, the potential for improvement there is very very limited), for more details see our paper.

> Another question: Maybe in network A, the input of relu is a two dimension Tensor; in network B, the input of relu is a four dimension Tensor. What should I do?

You can implement multiple versions of ReLU or you can create a simple generator that takes a tensor and returns a TC string of the proper dimensionality. If this sounds useful we could easily implement such a higher level functionality as a library that you could use as such:

```
auto some_tensor({M, N, P});
std::string tc = tc::ReLU(some_tensor);
``` 

Would that be useful?

**Comment by QiJune** [comment]
@nicolasvasilache Thanks! That's quite useful!
