### ISSUE TITLE
Indexing a tensor with a tensor on LHS of equation

### ISSUE THREAD

**Issue by pclucas14** [facebookresearch/TensorComprehensions#446]
Hello, 

I'm getting an error when trying to do the following
`points_bw(b, indices(b, n, k), y) -=  ... `

is this type of indexing not supported in the Tensor Comprehensions framework ? 

Thanks, 
Lucas

**Comment by ftynse** [comment]
Support for that is in progress (#262 #9).  There will be restrictions on what `indices` contain though, in particular, the same expression should not be writing twice in the same element (i.e. all values of `indices(b, n, k)` must be unique.

**Comment by pclucas14** [comment]
I see, thanks for the quick answer!

**Comment by ftynse** [comment]
I'll close this issue in favor of the two earlier ones.  Please subscribe to those if you want to get an update on when the support is added.
