### ISSUE TITLE
Do not store mapping options proto after tuning unless explicitly asked to

### ISSUE THREAD

**Issue by ftynse** [facebookresearch/TensorComprehensions#473]
alternatively, do not automatically pick up those options.  It appears that TC currently stores and picks up options from `/tmp` silently.  This is a confusing behavior that makes it look like the autotuner works much better in some cases than it actually does.  It is very problematic if the behavior of the mapper changed and the previously stored options are used.

**Comment by nicolasvasilache** [comment]
This is done implicitly in the `autotuner.tune` when passing a file, we should make it explicit.
Either have 2 tuning calls, but even better just expose a simple API for cache loading and storing that we can reuse and compose a load call with tune explicitly if we want to start from an existing state.

**Comment by nicolasvasilache** [comment]
Atm we have implicit load and implicit store if a non-empty filename is passed (i.e. either "reinforce behavior" either "forget the world behavior").

However I turn this, it seems much more error prone to break the symmetry.
The only logical conclusion is to totally decouple tuning from storage in the C++ API, so tune will not take a filename anymore and whoever wants to reinforce from C++ will have to explicitly load from file, tune and then store to file.

Note that in the python API we most likely want to hide that complexity so passing a filename will be synonymous with "reinforce behavior".

Shout if you disagree on the claim that having an implicit assymmetric behavior will be quite more confusing.

**Comment by ftynse** [comment]
I don't think asymmetry is a problem. This is essentially saving and
loading files. I doubt there is a potential user who is not familiar with
the concept of files.

Implicitness is a problem. Leaky abstratctions are a problem.  HCI 101:
users build a mental model of how your program works based on the state
they can observe (and almost nobody reads the docs past the first example).
When their mental model does not match how your program works, errors and
frustration appear. Explicit files are a much safer bet for the mental
model than saving something somewhere under the hood.

What happens if the user wants to overwrite the saved options with newly
generated ones, say after changing TC version? Well, they have to remember
that there is some file with long name in /tmp and delete it...  What
happens if somebody cleaned /tmp between runs, or worse, overwrote that
file with some other options?  If your goal is to make the use of TC tuner
unambiguous, this "implicit reinforce" is going in the opposite direction.

I agree that there should be a separate functionality for saving and
loading options. This is a clean separation of concerns. The tuner now
returns the list of options, and there is no segfault,  let the caller
decide what they want to do with it.

I disagree that there should be a different python API. We should take the
opportunity given by current refactoring and clean that up, make the API as
close as possible to C++. In python, there is the PEP20 document saying
"explicit is better than implicit". Unfortunately, many python interfaces
went into more JavaScript style APIs with functions that do different
things depending on some optional parameters. I'd rather not do that.
