### ISSUE TITLE
test_mapper_llvm fails because wrong cilkrts is found

### ISSUE THREAD

**Issue by skimo-openhub** [facebookresearch/TensorComprehensions#49]
With ac1f3c34aed50c7abb984420eceb1e01fd39ccc2, I get
```
Running build/test/test_mapper_llvm
[==========] Running 4 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 4 tests from LLVMCodegen
[ RUN      ] LLVMCodegen.Basic
unknown file: Failure
C++ exception with description "Failed to find cilkrts: /usr/lib32/libcilkrts.so.5: wrong ELF class: ELFCLASS32" thrown in the test body.
[  FAILED  ] LLVMCodegen.Basic (12 ms)
```
The output of `ldconfig -p | grep libcilkrts` is
```
        libcilkrts.so.5 (libc6,x32) => /usr/libx32/libcilkrts.so.5
        libcilkrts.so.5 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcilkrts.so.5
        libcilkrts.so.5 (libc6) => /usr/lib32/libcilkrts.so.5
```

**Comment by ttheodor** [comment]
Here's the offending code: https://github.com/facebookresearch/TensorComprehensions/blob/master/src/core/polyhedral/llvm_jit.cc#L38

**Comment by prigoyal** [comment]
@wsmoses we can make change to the build system to only look for 64-bit cilk runtime.

**Comment by skimo-openhub** [comment]
On Thu, Feb 22, 2018 at 10:21:47AM +0000, ftynse wrote:
> I have a different variation of this
> ```
> sh: 1: ldconfig: not found      
> unknown file: Failure                                      
> C++ exception with description "Failed locate library: libcilkrts.so" thrown in the test body.
> ```
> 
> On Debian, `ldconfig` is located in `/sbin` and not in the path for a regular user.  It looks like we need a better process of loading the library...

I think Priya was proposing to look for the library at configure/build
time instead of at run time.

skimo

**Comment by prigoyal** [comment]
yes, I was proposing to do it at configure/build time. If this test if blocking then feel free to disable the test for now. Billy is traveling I think for some talk so might not be available for this.

**Comment by wsmoses** [comment]
@skimo-openhub 
I made a quick fix to only search for 64bit libraries here: https://github.com/facebookresearch/TensorComprehensions/tree/tfix

This doesn't stop the fact that we should fix this, but perhaps this will unblock you.
