### ISSUE TITLE
Missing mapping filter when the outer band has no child.

### ISSUE THREAD

**Issue by math-fehr** [facebookresearch/TensorComprehensions#525]
When the outer band has no child, there is no mapping filter inserted.
It can be seen in the tc
```
def f(float(N) I) -> (a)
{
    a = 0
}
```
which produce a kernel using all the threads to do the a[0] = 0 instruction.

**Comment by skimo-openhub** [comment]
> which produce a kernel using all the threads to do the a[0] = 0 instruction.

Is that a problem? In practice, "all the threads" just means the single thread because
tightening will ensure this only gets run on a single thread.

**Comment by skimo-openhub** [comment]
On Tue, Jun 19, 2018 at 11:25:35AM +0000, ftynse wrote:
> Tightening does not pick that up.

I was going to ask you meant, but I guess the problem
is that tightening needs a mapping in the first place.
(I was confused because when I tried it out,
I did see the block getting tightened to a single thread.)

skimo
