### ISSUE TITLE
[Build] error: expected type-specifier for llvm::CilkABI()

### ISSUE THREAD

**Issue by Banus** [facebookresearch/TensorComprehensions#53]
I'm trying to build the TC project from the docker images and default settings, but I'm stuck with the following error:

```C++
/root/TensorComprehensions/src/core/polyhedral/codegen_llvm.cc: In member function 'void tc::polyhedral::{anonymous}::CodeGen_TC::optimize_module()':
/root/TensorComprehensions/src/core/polyhedral/codegen_llvm.cc:331:25: error: expected type-specifier
     b.tapirTarget = new llvm::CilkABI();
```
I'm using the following docker image to automate the build, using the command `docker build -t tc-local .` to build:

```docker
FROM tensorcomprehensions/linux-xenial-gcc5-tapir5.0-cuda9-cudnn7-py3:x86

ENV DEBIAN_FRONTEND noninteractive

RUN cd /root && \
  git clone https://github.com/facebookresearch/TensorComprehensions.git --recursive

ENV TC_DIR=/root/TensorComprehensions
RUN cd ${TC_DIR} && \
  git submodule update --init --recursive && \
  BUILD_TYPE=Release PYTHON=$(which python3) WITH_CAFFE2=OFF ./build.sh --all
```

I had to remove the manual `CLANG_HOME` environmental variable from the [instructions](https://facebookresearch.github.io/TensorComprehensions/installation_non_conda.html#non-conda-install-tc) because in the docker image the LLVM location is different and already specified in `CLANG_HOME`. 

Configuration
- OS: _Ubuntu 14.04_
- How you installed TC: _docker_
- Python version: _Python 3.5.2_
- CUDA/cuDNN version: _CUDA v9.1.85_, _cuDNN 7_
- Conda version (is using conda): _None_
- Docker image (if using docker): `tensorcomprehensions/linux-xenial-gcc5-tapir5.0-cuda9-cudnn7-py3:x86`
- GCC/GXX version (if compiling from source): _5.4.1_
- LLVM/Tapir git hash used (if compiling from source): _5.0.0_

Commit hash of the repo:

    32414e3ef77215a0bea834dccdc85b046a66f02f

Commit hash of all the submodules: [gist](https://gist.github.com/Banus/491826818b4e92dde58864047cc4e55b)

**Comment by ftynse** [comment]
> I had to remove the manual CLANG_HOME environmental variable from the instructions because in the docker image the LLVM location is different and already specified in CLANG_HOME.

I don't recall us using `CLANG_HOME`, there is `CLANG_PREFIX` however.  Without this variable, the build script maybe picking up a wrong LLVM.

**Comment by ftynse** [comment]
You may also try `ensorcomprehensions/linux-xenial-gcc5-tapir5.0-cuda9-cudnn7-py3:x86_1` image (note the `_1`).

**Comment by wsmoses** [comment]
Tapir/LLVM was bumped in the docker image by @prigoyal .

Specifying the newer docker image tensorcomprehensions/linux-xenial-gcc5-tapir5.0-cuda9-cudnn7-py3:x86_1 as @ftynse said should resolve

**Comment by Banus** [comment]
Thanks @ftynse, @wsmoses and @prigoyal, I'll try the new image tomorrow.

@ftynse you are right, the environmental variable is `CLANG_PREFIX`; I got it somewhat mixed with `HOME`.
