### ISSUE TITLE
tc.decode() results in "compilation_cache.proto: No such file or directory"

### ISSUE THREAD

**Issue by concretevitamin** [facebookresearch/TensorComprehensions#538]
- Commit hash of our repo and submodules (if compiling from source): cc4b1eb991245c6d83d9082cfe05b4189b78cc16

I was trying out autotuning on the vanilla convolution example:
```python
import numpy as np
import tensor_comprehensions as tc
import torch

lang = """
def convolution(float(N, C, H, W) I, float(M, C, KH, KW) W1) -> (O) {
    O(n, m, h, w) +=! I(n, c, h + kh, w + kw) * W1(m, c, kh, kw)
}
"""
convolution = tc.define(lang, name="convolution")
inp = torch.randn(1, 2, 24, 24).cuda()
weights = torch.randn(6, 2, 1, 1).cuda()
convolution.autotune(inp, weights, generations=1, cache='my_convolution')
```
Then,
```
In [9]: tc.decode("<path>/my_convolution.options")
.../anaconda3/envs/tc_build/lib/python3.6/site-packages/tensor_comprehensions/compilation_cache.proto: No such file or directory
```
I can see that the `my_convolution.options` is indeed generated and non-empty.

**Comment by nicolasvasilache** [comment]
@concretevitamine we are in the process if updating and retiring some of
the python-side API.

I seem to remember you build from source is this accurate?
If so, the best would be to get the branch from PR #531 (branch pr/python)
and use that for now.
We will update the TC conda packages soon but tc.decode is being retired.

If you look at test_tc.py in that PR you will see the supported ways to use
the new low-overhead python abstraction; I'll update the documentation in
the next few days.

Lastly, I will reiterate that TC does not implement optimizations for
compute-bound convolutions and gemm at this time; you should be better off
using cudnn in this specific case.

**Comment by concretevitamin** [comment]
On Mon, Jun 25, 2018 at 11:28 AM Nicolas Vasilache <notifications@github.com>
wrote:

> @concretevitamine we are in the process if updating and retiring some of
> the python-side API.
>
> I seem to remember you build from source is this accurate?
> If so, the best would be to get the branch from PR #531 (branch pr/python)
> and use that for now.
> We will update the TC conda packages soon but tc.decode is being retired.
>
> If you look at test_tc.py in that PR you will see the supported ways to use
> the new low-overhead python abstraction; I'll update the documentation in
> the next few days.
>
> Lastly, I will reiterate that TC does not implement optimizations for
> compute-bound convolutions and gemm at this time; you should be better off
> using cudnn in this specific case.
>

Thanks Nicolas.  I will try to build off from that PR.

Fully noted re: compute-bound ops.

**Comment by nicolasvasilache** [comment]
`tc.decode` is now deprecated.
