### ISSUE TITLE
module 'tensor_comprehensions' has no attribute 'make_naive_options_factory'

### ISSUE THREAD

**Issue by keightyfive** [facebookresearch/TensorComprehensions#593]
Hi,

I'm trying to run a simple example to get started with understanding the different mapping options (https://facebookresearch.github.io/TensorComprehensions/framework/pytorch_integration/getting_started.html). 

When trying to run the first example the code throws:
` Traceback (most recent call last):
  File "matmul.py", line 8, in <module>
    TC = tc.define(mm, tc.make_naive_options_factory())
AttributeError: module 'tensor_comprehensions' has no attribute 'make_naive_options_factory'
`
I have the TC Conda package installed (https://facebookresearch.github.io/TensorComprehensions/installation.html#conda-installation).

Cheers,
Kevin

**Comment by nicolasvasilache** [comment]
Hi Kevin,

We currently do not have an up to date conda package, we are waiting for
pytorch 1.0 to make this available.
You want to build from source to get the latest API.

Best,

N

**Comment by keightyfive** [comment]
Thanks Nic,

I've been experiencing quite a good amount of issues with the build, see issue #407 
Which is why I turned to the Conda package but if I want to dog deeper I guess there's no way getting around the build.
Do you have any further assumptions on why the auto detection fails?

Cheers, Kevin

**Comment by nicolasvasilache** [comment]
Hi Kevin,

The build system has been significantly overhauled and simplified.
In particular we do not try to build ATen anymore but we use the prebuilt
pytorch packages.
The new instructions
@https://facebookresearch.github.io/TensorComprehensions/installation.html#build-from-source
reflect this.

One thing to be mindful of atm is that the pytorch nightly packages have
been changing recently and we do not  yet support those so you should use
version 0.4.0 explicitly for now:
```

conda install -y -c pytorch pytorch=0.4.0 torchvision cuda90

```

**Comment by keightyfive** [comment]
Thanks for keeping me updated Nic,
I think I'll try installing the Docker image tomorrow and see if I can then play around with the various mapping options and the Autotuner a bit...

Cheers, Kevin

**Comment by keightyfive** [comment]
Hi Nic,

I finally managed to build TC from source, thank you for your help. I used pytorch version 0.4.0 as you suggested.

The C++ tests seem to have run just fine.

To run the python tests, the script seems to have shifted, so the cmd is currently
python ./python/tests/test_tc.py -v if you want to update this in the documentation.

The tests for python throws 1 or 2 errors at:
test_tc_llvm (__main__.TestTC) ... In file included from <built-in>:1:
/usr/local/lib/clang/5.0.0/include/__clang_cuda_runtime_wrapper.h:66:2: error: "Unsupported CUDA version!"
#error "Unsupported CUDA version!"
 ^
/usr/local/lib/clang/5.0.0/include/__clang_cuda_runtime_wrapper.h:108:10: fatal error: 'crt/device_runtime.h' file not found
#include "crt/device_runtime.h"
         ^~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
ERROR
======================================================================
ERROR: test_tc_llvm (__main__.TestTC)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./python/tests/test_tc.py", line 85, in test_tc_llvm
    A, B,
  File "/home/kklein/TensorComprehensions/tensor_comprehensions/__init__.py", line 143, in compile
    return Executor(tclib.compile(tc, entry_point, inputs, mapping_options))
RuntimeError: Check failed [/home/kklein/TensorComprehensions/tc/core/cuda/cuda_rtc.cc:76] 256 not equal to 0: /,u,s,r,/,l,o,c,a,l,/,b,i,n,/,c,l,a,n,g,+,+, ,-,x, ,c,u,d,a, ,/,t,m,p,/,c,u,d,a,n,Z,O,T,T,5, ,-,-,c,u,d,a,-,d,e,v,i,c,e,-,o,n,l,y, ,-,-,c,u,d,a,-,g,p,u,-,a,r,c,h,=,s,m,_,3,5, ,-,-,c,u,d,a,-,p,a,t,h,=,/,u,s,r,/,l,o,c,a,l,/,c,u,d,a, ,-,I,/,u,s,r,/,l,o,c,a,l,/,c,u,d,a,/,i,n,c,l,u,d,e, ,-,I,/,h,o,m,e,/,k,k,l,e,i,n,/,T,e,n,s,o,r,C,o,m,p,r,e,h,e,n,s,i,o,n,s,/,t,h,i,r,d,-,p,a,r,t,y,-,i,n,s,t,a,l,l,/,i,n,c,l,u,d,e, ,-,s,t,d,=,c,+,+,1,1, ,-,O,3, ,-,f,f,a,s,t,-,m,a,t,h, ,-,n,o,c,u,d,a,l,i,b, ,-,S, ,-,e,m,i,t,-,l,l,v,m, ,-,o, ,/,t,m,p,/,c,u,d,a,n,Z,O,T,T,5,-,c,l,a,n,g,.,l,l, 
----------------------------------------------------------------------
Ran 15 tests in 262.206s
FAILED (errors=1)

__main__.TestTC worked ok. Do you think the error is critical?

Cheers, Kevin

**Comment by nicolasvasilache** [comment]
Hi Kevin,

The particular test is a test for JIT compiling with LLVM instead of NVRTC.
If LLVM (compiled for the NVPTX backend) is not present the test will fail.
You can safely ignore locally.

N

**Comment by keightyfive** [comment]
Thanks Nic,

Before I close the topic, I have one last question:

When you now run the basic example like gconv to start with, the line
matmul = tc.define(lang, name="matmul")
will throw the error
Traceback (most recent call last):
  File "gconv1.py", line 11, in <module>
    gconv = tc.define(lang, name="gconv")
TypeError: define() got an unexpected keyword argument 'name'

So I went on to replace name="gconv" with tc.make_naive_options_factory() or just simply "gconv".
When profiling the program with nvprof however, the behaviour now seems to be different in a sense that the code doesn't seem to be running on the device any more, instead there seems to be a copy made from device to host, and from host to device (which I don't really understand either as it would make more sense to me the other way around).
Also, I find it confusing that in the first case, there seems to be a copy made from host to device, but I can't see the results being copied back to the host. (There's also tone of intermediate results being printed, which wasn't the case with the conda package and I'd like to switch this off if possible.)

Here are the profiling outputs:
1) Conda version:
==22165== Profiling application: python gconv1.py
==22165== Profiling result:
Time(%)      Time     Calls       Avg       Min       Max  Name
 99.93%  17.6032s         1  17.6032s  17.6032s  17.6032s  gconv_16_16_32_14_14_14_32_14
  0.07%  11.931ms         3  3.9769ms  1.7600us  10.592ms  [CUDA memcpy HtoD]
  0.00%  1.8400us         1  1.8400us  1.8400us  1.8400us  [CUDA memset]

==22165== API calls:
Time(%)      Time     Calls       Avg       Min       Max  Name
 77.25%  17.5640s         1  17.5640s  17.5640s  17.5640s  cuModuleUnload
 22.57%  5.13201s         3  1.71067s  295.56us  5.13119s  cudaMalloc
  0.09%  21.554ms         1  21.554ms  21.554ms  21.554ms  cuModuleLoadDataEx
  0.06%  14.095ms         3  4.6983ms  15.300us  12.681ms  cudaMemcpyAsync
  0.01%  2.1008ms         4  525.19us  513.24us  545.72us  cudaGetDeviceProperties
  0.00%  1.0966ms       180  6.0920us     246ns  233.11us  cuDeviceGetAttribute
  0.00%  290.36us         2  145.18us  140.53us  149.83us  cuDeviceTotalMem
  0.00%  208.42us         3  69.472us  9.7660us  171.55us  cudaStreamSynchronize
  0.00%  182.40us         2  91.200us  89.229us  93.171us  cuDeviceGetName
  0.00%  77.927us        29  2.6870us     544ns  16.465us  cudaGetDevice
  0.00%  42.005us         1  42.005us  42.005us  42.005us  cuLaunchKernel
  0.00%  37.005us         7  5.2860us  1.7060us  11.824us  cudaPointerGetAttributes
  0.00%  30.901us         1  30.901us  30.901us  30.901us  cudaMemsetAsync
  0.00%  29.128us         7  4.1610us     805ns  13.233us  cudaSetDevice
  0.00%  9.0620us         7  1.2940us     279ns  6.3410us  cudaGetDeviceCount
  0.00%  5.8210us         4  1.4550us     397ns  3.8370us  cuDeviceGetCount
  0.00%  3.2500us         5     650ns     330ns  1.2170us  cuDeviceGet
  0.00%  2.4520us         1  2.4520us  2.4520us  2.4520us  cuDriverGetVersion
  0.00%  2.1300us         1  2.1300us  2.1300us  2.1300us  cuInit
  0.00%  1.0510us         1  1.0510us  1.0510us  1.0510us  cuModuleGetFunction
  0.00%     608ns         1     608ns     608ns     608ns  cudaGetLastError


2) After building from source:
==12597== Profiling application: python gconv1.py
==12597== Profiling result:
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:   69.56%  27.224ms     15587  1.7460us  1.0240us  6.8758ms  [CUDA memcpy DtoH]
                   30.44%  11.912ms        11  1.0829ms     928ns  9.9326ms  [CUDA memcpy HtoD]
      API calls:   94.91%  10.2278s         3  3.40926s  708.09us  10.2261s  cudaMalloc
                    3.20%  345.04ms     15590  22.132us  15.265us  11.784ms  cudaMemcpyAsync
                    0.83%  89.199ms     78956  1.1290us     562ns  934.78us  cudaGetDevice
                    0.61%  65.438ms     15590  4.1970us  3.0600us  1.8273ms  cudaStreamSynchronize
                    0.42%  44.754ms     39471  1.1330us     711ns  970.28us  cudaSetDevice
                    0.01%  1.2470ms       185  6.7400us     246ns  310.13us  cuDeviceGetAttribute
                    0.01%  1.1066ms         2  553.29us  544.71us  561.87us  cudaGetDeviceProperties
                    0.01%  568.77us         2  284.38us  256.74us  312.03us  cuDeviceTotalMem
                    0.00%  441.46us         8  55.182us  12.435us  272.42us  cudaMemcpy
                    0.00%  153.33us         2  76.662us  67.712us  85.613us  cuDeviceGetName
                    0.00%  40.248us        12  3.3540us     254ns  30.996us  cudaGetDeviceCount
                    0.00%  21.517us         2  10.758us  2.3630us  19.154us  cudaGetLastError
                    0.00%  6.1990us         4  1.5490us     406ns  4.7950us  cuDeviceGetCount
                    0.00%  2.2330us         3     744ns     340ns  1.0240us  cuDeviceGet
                    0.00%  1.1980us         1  1.1980us  1.1980us  1.1980us  cuInit
                    0.00%  1.0460us         1  1.0460us  1.0460us  1.0460us  cuDriverGetVersion

Cheers, Kevin
