### ISSUE TITLE
[Build] Aten library cannot be found, incomplete config

### ISSUE THREAD

**Issue by yaozhujia** [facebookresearch/TensorComprehensions#602]
Hello everyone from TC,

I followed the [installation guide](https://facebookresearch.github.io/TensorComprehensions/installation.html) of TC. conda cannot install Aten library successfully.

Below is the filled template for a build issue.

- OS: Ubuntu 16.04
- How you installed TC (docker, conda, source): conda
- Python version: Python 3.6.6 :: Anaconda, Inc.
- CUDA/cuDNN version: CUDA9.2, cuDNN v7.2.1
- Conda version (if using conda): conda 4.5.10
- Docker image (if using docker):
- GCC/GXX version (if compiling from source): gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)
- LLVM/Tapir git hash used (if compiling from source): clang version 7.0.0 (trunk 336729)
                                                                                      Target: x86_64-unknown-linux-gnu
                                                                                      Thread model: posix

- Commit hash of our repo and submodules (if compiling from source): 00caa7d7c89ee158f716791c327849362c5d062c

In addition, including the following information will also be very helpful for us to diagnose the problem:
- A script to reproduce the issue (highly recommended if its a build issue)

I followed the installation guide and the issue was encountered when executing the command

CLANG_PREFIX=$(${CONDA_PREFIX}/bin/llvm-config --prefix) ./build.sh

- Error messages and/or stack traces of the issue (create a gist)

+++ dirname ./build.sh
++ cd .
++ pwd
+ export TC_DIR=/home/jiezhao/Projects/TensorComprehensions
+ TC_DIR=/home/jiezhao/Projects/TensorComprehensions
+ test /home/jiezhao/Projects/anaconda/envs/tc_build
+ test /home/jiezhao/Projects/anaconda/envs/tc_build
++ which python3
+ PYTHON=/home/jiezhao/Projects/anaconda/envs/tc_build/bin/python3
++ which gcc
+ CC=/usr/bin/gcc
++ which g++
+ CXX=/usr/bin/g++
+ WITH_CUDA=ON
+ WITH_CAFFE2=OFF
+ WITH_TAPIR=ON
+ WITH_BINDINGS=OFF
+ CUDNN_ROOT_DIR=/home/jiezhao/Projects/anaconda/envs/tc_build
+ CMAKE_PREFIX_PATH=/home/jiezhao/Projects/anaconda/envs/tc_build/lib/cmake
+ HALIDE_PREFIX=/home/jiezhao/Projects/anaconda/envs/tc_build
+ EIGEN_PREFIX=/home/jiezhao/Projects/anaconda/envs/tc_build
+ CAFFE2_PREFIX=/home/jiezhao/Projects/anaconda/envs/tc_build
+ THIRD_PARTY_INSTALL_PREFIX=/home/jiezhao/Projects/TensorComprehensions/third-party-install
+ INSTALL_PREFIX=/home/jiezhao/Projects/TensorComprehensions/install
+ mkdir -p /home/jiezhao/Projects/TensorComprehensions/install
+ echo 'TC_DIR: ' /home/jiezhao/Projects/TensorComprehensions
TC_DIR:  /home/jiezhao/Projects/TensorComprehensions
+ echo 'GCC_VER: '
GCC_VER: 
+ BUILD_TYPE=Debug
+ echo 'Build Type: Debug'
Build Type: Debug
+ mkdir -p /home/jiezhao/Projects/TensorComprehensions/build
+ cd /home/jiezhao/Projects/TensorComprehensions/build
+ echo 'Installing TC'
Installing TC
+ rm -Rf /home/jiezhao/Projects/TensorComprehensions/install
+ cmake -DWITH_CAFFE2=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DWITH_TAPIR=ON -DPYTHON_EXECUTABLE=/home/jiezhao/Projects/anaconda/envs/tc_build/bin/python3 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH=/home/jiezhao/Projects/anaconda/envs/tc_build/lib/cmake -DHALIDE_PREFIX=/home/jiezhao/Projects/anaconda/envs/tc_build -DEIGEN_PREFIX=/home/jiezhao/Projects/anaconda/envs/tc_build -DCAFFE2_PREFIX=/home/jiezhao/Projects/anaconda/envs/tc_build -DTHIRD_PARTY_INSTALL_PREFIX=/home/jiezhao/Projects/TensorComprehensions/third-party-install -DCMAKE_INSTALL_PREFIX=/home/jiezhao/Projects/TensorComprehensions/install -DCLANG_PREFIX=/home/jiezhao/Projects/anaconda/envs/tc_build -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-9.2/ -DCUDNN_ROOT_DIR=/home/jiezhao/Projects/anaconda/envs/tc_build -DWITH_CUDA=ON -DTC_DIR=/home/jiezhao/Projects/TensorComprehensions -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ ..
CMake Warning (dev) at CMakeLists.txt:15 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    CMAKE_PROJECT_VERSION
    CMAKE_PROJECT_VERSION_MAJOR
    CMAKE_PROJECT_VERSION_MINOR
    CMAKE_PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

make  all-recursive
make[1]: Entering directory '/home/jiezhao/Projects/TensorComprehensions/third-party/googlelibraries/protobuf-3.5.2'
Making all in .
make[2]: Entering directory '/home/jiezhao/Projects/TensorComprehensions/third-party/googlelibraries/protobuf-3.5.2'
make[2]: Leaving directory '/home/jiezhao/Projects/TensorComprehensions/third-party/googlelibraries/protobuf-3.5.2'
Making all in src
make[2]: Entering directory '/home/jiezhao/Projects/TensorComprehensions/third-party/googlelibraries/protobuf-3.5.2/src'
make  all-am
make[3]: Entering directory '/home/jiezhao/Projects/TensorComprehensions/third-party/googlelibraries/protobuf-3.5.2/src'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/jiezhao/Projects/TensorComprehensions/third-party/googlelibraries/protobuf-3.5.2/src'
make[2]: Leaving directory '/home/jiezhao/Projects/TensorComprehensions/third-party/googlelibraries/protobuf-3.5.2/src'
make[1]: Leaving directory '/home/jiezhao/Projects/TensorComprehensions/third-party/googlelibraries/protobuf-3.5.2'
Found PROTOBUF_LIBRARIES:/home/jiezhao/Projects/TensorComprehensions/third-party/googlelibraries/protobuf-3.5.2/src/.libs/libprotobuf.a
Found PROTOBUF_PROTOC_EXECUTABLE:/home/jiezhao/Projects/TensorComprehensions/third-party/googlelibraries/protobuf-3.5.2/src/protoc
Found PROTOBUF_INCLUDES:/home/jiezhao/Projects/TensorComprehensions/third-party/googlelibraries/protobuf-3.5.2/src
-- Automatic GPU detection failed. Building for common architectures.
-- Autodetected CUDA architecture(s): 3.0;3.5;5.0;5.2;6.0;6.1;6.1+PTX
-- Found CUDNN: /home/jiezhao/Projects/anaconda/envs/tc_build/include  
-- Found cuDNN: v7.2.1  (include: /home/jiezhao/Projects/anaconda/envs/tc_build/include, library: /home/jiezhao/Projects/anaconda/envs/tc_build/lib/libcudnn.so)
-- Looking for LLVM in /home/jiezhao/Projects/anaconda/envs/tc_build/lib/cmake/llvm
-- Found LLVM 7.0.0svn
-- Using LLVMConfig.cmake in: /home/jiezhao/Projects/anaconda/envs/tc_build/lib/cmake/llvm
-- pybind11 v2.2.1
-- PYTHON output: 
/home/jiezhao/Projects/anaconda/envs/tc_build/bin/python
-- IMPORTING TORCH: 
0
-- PYTHON site packages: 
/home/jiezhao/Projects/anaconda/envs/tc_build/lib/python3.6/site-packages
-- TORCH INSTALLED, linking to ATen from PyTorch
-- Found ATen.so file: ATEN_LIBRARIES-NOTFOUND
-- Finding Halide
-- HALIDE_INCLUDE_DIRS: /home/jiezhao/Projects/anaconda/envs/tc_build/include
-- Found Halide.so file: /home/jiezhao/Projects/anaconda/envs/tc_build/lib/libHalide.so
include(cmake/GetGitRevisionDescription.cmake)
-- BUILD_TYPE: Debug
-- CMAKE_CXX_COMPILER_VERSION is 5.4.0
-- CMAKE_CXX_FLAGS is  -Wall -Wno-unused-variable -Werror -Wno-sign-compare
-- CMAKE_CXX_FLAGS_DEBUG is -g
-- CMAKE_INSTALL_PREFIX is /home/jiezhao/Projects/TensorComprehensions/install
-- HEAD FILE: /home/jiezhao/Projects/TensorComprehensions/build/tc/version/CMakeFiles/git-data/HEAD
-- Not building benchmarks, caffe2 or CUDA not available
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ATEN_LIBRARIES
    linked by target "tc_autotuner" in directory /home/jiezhao/Projects/TensorComprehensions/tc/autotuner
    linked by target "test_basic" in directory /home/jiezhao/Projects/TensorComprehensions/test
    linked by target "test_mapper_llvm" in directory /home/jiezhao/Projects/TensorComprehensions/test
    linked by target "test_compile_and_run" in directory /home/jiezhao/Projects/TensorComprehensions/test/cuda
    linked by target "test_compilation_cache" in directory /home/jiezhao/Projects/TensorComprehensions/test/cuda
    linked by target "test_autotuner_utility" in directory /home/jiezhao/Projects/TensorComprehensions/test/cuda
    linked by target "test_tc_mapper_bugs" in directory /home/jiezhao/Projects/TensorComprehensions/test/cuda
    linked by target "test_corner_cases" in directory /home/jiezhao/Projects/TensorComprehensions/test/cuda
    linked by target "test_tc_mapper" in directory /home/jiezhao/Projects/TensorComprehensions/test/cuda
    linked by target "test_autotuner" in directory /home/jiezhao/Projects/TensorComprehensions/test/cuda
    linked by target "group_normalization" in directory /home/jiezhao/Projects/TensorComprehensions/tc/examples
    linked by target "blockdiagperm" in directory /home/jiezhao/Projects/TensorComprehensions/tc/examples
    linked by target "tensordot" in directory /home/jiezhao/Projects/TensorComprehensions/tc/examples

-- Configuring incomplete, errors occurred!
See also "/home/jiezhao/Projects/TensorComprehensions/build/CMakeFiles/CMakeOutput.log".
See also "/home/jiezhao/Projects/TensorComprehensions/build/CMakeFiles/CMakeError.log".
+ exit 1

- Context around what you are trying to do

I installed the pytorch conda package, but I didn't find the libAten.so file in the directory /home/jiezhao/Projects/anaconda/envs/tc_build/lib/python3.6/site-packages/

Thanks.

Jie

**Comment by skimo-openhub** [comment]
On Sun, Aug 26, 2018 at 02:16:10PM -0700, yaozhujia wrote:
> Hello everyone from TC,
> 
> I followed the [installation guide](https://facebookresearch.github.io/TensorComprehensions/installation.html) of TC. conda cannot install Aten library successfully.

They appear to be slightly outdated.
You specifically need to install version 0.4.0 of pytorch

conda install -y -c pytorch pytorch=0.4.0 torchvision cuda90

See #598.

skimo

**Comment by Crazytravy07** [comment]
sudo apt-get install libgmp3-dev cmake automake libtool

**Comment by ftynse** [comment]
> sudo apt-get install libgmp3-dev cmake automake libtool

This looks irrelevant to the issue.  cmake is cleary running.

The answer from @skimo-openhub should fix the issue.

**Comment by yaozhujia** [comment]
> On 27 Aug 2018, at 09:05, skimo-openhub <notifications@github.com> wrote:
> 
> On Sun, Aug 26, 2018 at 02:16:10PM -0700, yaozhujia wrote:
> > Hello everyone from TC,
> > 
> > I followed the [installation guide](https://facebookresearch.github.io/TensorComprehensions/installation.html) of TC. conda cannot install Aten library successfully.
> 
> They appear to be slightly outdated.
> You specifically need to install version 0.4.0 of pytorch
> 
> conda install -y -c pytorch pytorch=0.4.0 torchvision cuda90
> 
> See #598.

Indeed. It works now. Thanks.

Jie

**Comment by ftynse** [comment]
I've updated the documentation in the meantime.
