### ISSUE TITLE
Is there support for pytorch 1.x ?

### ISSUE THREAD

**Issue by pclucas14** [facebookresearch/TensorComprehensions#616]
Hi, 

I'm unable to install tensor comprehensions with pytorch 1.0. (Conda requires me to downgrade to pytorch 0.4). Is this normal ? If so, when is support for pytorch 1.x expected ?

Thanks!
Lucas

**Comment by nicolasvasilache** [comment]
Hello, unfortunately, the project is not maintained anymore and no future changes are planned.

**Comment by pclucas14** [comment]
It was a really cool project while it lasted. Thanks for the answer
