### ISSUE TITLE
Is the project still under development? 

### ISSUE THREAD

**Issue by Lyken17** [facebookresearch/TensorComprehensions#619]
Hi there,

I notice the latest update was May 2018. I am curious whether the project is still developing? Or facebook has switched to [tvm](https://github.com/dmlc/tvm) or [glow](https://github.com/pytorch/glow)?

**Comment by nicolasvasilache** [comment]
Hello, unfortunately, the project is not maintained anymore and no future changes are planned.

**Comment by Lyken17** [comment]
Oh,  sorry to hear that. Anyway, thanks for your reply.

**Comment by speedcell4** [comment]
is there any technical reason for giving up this project? the official suggestion is moving to glow?
