### ISSUE TITLE
[Build] dockerfile build failed, source code compilation failed

### ISSUE THREAD

**Issue by dcslin** [facebookresearch/TensorComprehensions#620]
Tensor Comprehensions Github Issues Guidelines
----------------------------------------------

If you have a feature request or a bug report (build issue), please open an issue on Github and fill the template below so we can help you better and faster. If you have some general
questions about Tensor Comprehensions, please visit our [slack channel](https://tensorcomprehensions.herokuapp.com/) or email us at tensorcomp@fb.com

For build issues, please add `[Build]` at the beginning of issue title.

When submitting a bug report, please include the following information (where relevant):
- OS: Ubuntu 16.04
- How you installed TC (docker, conda, source): source
- Python version: the one in dockerfile
- CUDA/cuDNN version: host machine has cuda9, cudnn7
- Conda version (if using conda): the one in dockerfile
- Docker image (if using docker): dockerfile in master branch
- GCC/GXX version (if compiling from source): 
- LLVM/Tapir git hash used (if compiling from source):

  To get the hash, run: `$CONDA_PREFIX/bin/clang --version`

- Commit hash of our repo and submodules (if compiling from source):

In addition, including the following information will also be very helpful for us to diagnose the problem:
- A script to reproduce the issue (highly recommended if its a build issue)
docker build from dockerfile
- Error messages and/or stack traces of the issue (create a gist)

### error 1
`RUN test "$(/opt/conda/anaconda/bin/conda --version | grep 'conda 4.5')" != "" && echo Found conda 4.5.x as expected` return error code 1.

### error 2
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ATEN_LIBRARIES
    linked by target "tc_autotuner" in directory /root/TensorComprehensions/tc/autotuner
    linked by target "test_basic" in directory /root/TensorComprehensions/test
    linked by target "test_mapper_llvm" in directory /root/TensorComprehensions/test
    linked by target "test_autotuner" in directory /root/TensorComprehensions/test/cuda
    linked by target "test_autotuner_utility" in directory /root/TensorComprehensions/test/cuda
    linked by target "test_compile_and_run" in directory /root/TensorComprehensions/test/cuda
    linked by target "test_corner_cases" in directory /root/TensorComprehensions/test/cuda
    linked by target "test_tc_mapper_bugs" in directory /root/TensorComprehensions/test/cuda
    linked by target "test_compilation_cache" in directory /root/TensorComprehensions/test/cuda
    linked by target "test_tc_mapper" in directory /root/TensorComprehensions/test/cuda
    linked by target "tensordot" in directory /root/TensorComprehensions/tc/examples
    linked by target "group_normalization" in directory /root/TensorComprehensions/tc/examples
    linked by target "blockdiagperm" in directory /root/TensorComprehensions/tc/examples
PROTOBUF_LIBRARIES
    linked by target "tc_proto" in directory /root/TensorComprehensions/tc/proto
    linked by target "test_basic" in directory /root/TensorComprehensions/test
    linked by target "test_basic_gpu" in directory /root/TensorComprehensions/test/cuda

-- Configuring incomplete, errors occurred!
See also "/root/TensorComprehensions/build/CMakeFiles/CMakeOutput.log".
See also "/root/TensorComprehensions/build/CMakeFiles/CMakeError.log".
+ exit 1
```

- Context around what you are trying to do
try out tc and integrate tc into my project

Please kindly advise if the project is still active.

**Comment by nicolasvasilache** [comment]
Hello, unfortunately, the project is not maintained anymore and no future changes are planned.
