### ISSUE TITLE
Uniformize docker images 

### ISSUE THREAD

**Issue by nicolasvasilache** [facebookresearch/TensorComprehensions#76]
We used to have all our trusty docker images used to inherit from this ```FROM nvidia/cuda:8.0-cudnn6-devel-ubuntu14.04``` and all our xenial docker images used to inherit from this ```FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04```

This has changed drastically and I see that we now start from a naked ubuntu [image](https://github.com/facebookresearch/TensorComprehensions/blob/master/docker/linux-xenial/Dockerfile) unvetted by NVIDIA and we are installing cuda/cudnn with a custom [script](https://github.com/facebookresearch/TensorComprehensions/blob/master/docker/common/install_cuda.sh).

Still, when providing the Docker for conda_recipes we now use the NVIDIA [image](https://github.com/facebookresearch/TensorComprehensions/pull/72/files#diff-58bea0e3458359925d407be356a8aef7) again.

I would prefer that we only used the NVIDIA images like we had for months but let's discuss if something else makes more sense in a different CI context.

**Comment by prigoyal** [comment]
closing this and moving to new repo, we are getting new test CI in 1 week approx

new repo where docker will be maintined https://github.com/prigoyal/tensorcomp-dockerfiles

also, you are confusing the conda-recipe image , that doesn't run on CI but we still need to build packages in docker env for clean build and building packages require GPU, so we start from nvidia-docker. 

Closing this task, it confuses things. I am opening a new one about whether docker tiering should be done or not in new repo

**Comment by prigoyal** [comment]
Here is the task https://github.com/prigoyal/tensorcomp-dockerfiles/issues/4

please feel free to subscribe yourself and follow there.

**Comment by nicolasvasilache** [comment]
The conda-recipe image *running* on CI is unrelated to *factoring out* a common dockerfile and avoiding copy-pasta.

Sure we can discuss on that particular issue.

What is this "new repo" you're talking about?
Is it just a repository for maintaining the Docker files that used to in docker?
I assume there is a good reason for having a separate repo for this, I will ping @ezyang and @pietern to get more context.

**Comment by prigoyal** [comment]
please loop me in the discussions with @pietern and @ezyang

**Comment by prigoyal** [comment]
yes, for the separate repo, docker registry is going to be `registry.pytorch.org/tensorcomp`

On jenkins, when a new commit is pushed, the docker image build will kick-off again (as part of the Jenkins configuration I am writing for TC)

keeping the dockers images in this repo will kick off docker build everytime the PR is sent which we don't want. 

Hence, there are separate repo for keeping the docker files for pytorch, caffe2 etc as well

https://github.com/pietern/pytorch-dockerfiles/
https://github.com/pietern/caffe2-dockerfiles (this one is probably deprecated but not sure).

**Comment by prigoyal** [comment]
after more discussion with @pietern and @ezyang, we will remove the tiered docker images version. #79 issue will track that. 

thanks to @nicolasvasilache for starting the conversation on messenger, things cleared out a bit :)

**Comment by nicolasvasilache** [comment]
> I thought your task was that why we have nvidia-docker in conda recipe and hence we should do that for the CI images as well

Yes the goal of the task was to uniformize the images and the suggestion is to take the officially supported  NVIDIA images (like you did conda) as the base for anything related to GPU (unlike the CI image that starts from a naked ubuntu image and applies a cuda install script that we have to maintain and that AFAICT is not supported by NVIDIA).

Let's see what the next iteration of dockerfiles looks like in #79 then. 
The goal is to try and make our life easiest by reusing officially supported stuff :)
