### ISSUE TITLE
Avoid build.sh copy-pasta when having both conda and source mode

### ISSUE THREAD

**Issue by nicolasvasilache** [facebookresearch/TensorComprehensions#78]
#72 introduces a bunch of ```build.sh``` with content that is largely copy-pasted from the original ```build.sh```, it would be nice to structure things in a way such that:
  1. the main ```build.sh``` calls the auxiliary smaller build scripts with some set of options
  2. the conda recipes call the smaller build scripts with possibly another set of options

**Comment by prigoyal** [comment]
I am closing this task, this is based on misunderstanding about how conda packaging works. I can explain things in person or VC, whatever works. 

The build.sh in conda builds is not copy paste, it uses different env variable settings and I guess that's what matters for a build to work.
