### ISSUE TITLE
Docker images improvement - non tiered version

### ISSUE THREAD

**Issue by prigoyal** [facebookresearch/TensorComprehensions#79]
We need 4 docker files only:

gcc 4.8 - cuda8-cudnn6 - conda
gcc 4.8 - cuda8-cudnn6 - non conda

gcc 5 - cuda9-cudnn7 - conda
gcc 5 - cuda9-cudnn7 - non conda

as per discussion with @pietern and @ezyang, these images can be based off of nvidia docker images

**Comment by nicolasvasilache** [comment]
To save you some time, you want to reuse the images that we had been using in our CI pre-release that were spuriously [deleted](https://github.com/facebookresearch/TensorComprehensions/tree/747c0a6d8b0158abd89ff1f90963ef61a83f8fa1/docker/archive)

These were constructed in a tiered fashion to optimize docker image building on a laptop as I explained when I ramped you up through the process. 

AWS has different requirements that's fine, your safest bet is to take the proper tiered files and cat them together into a single file for each target you need.

**Comment by prigoyal** [comment]
@nicolasvasilache I would prefer to consolidate the current docker files - they use proper structure for writing dockerfiles and proper instructions to do so. I followed the docker official documentation for writing those, the instructions you had shown were not clear to me - they involved some other installation process for docker which was weird to me. Normal official documentation for docker works just fine as well.

**To be clear:**  the earlier docker files were not spuriously deleted, rather they were wrong. They were all testing conda env and not following the proper protocol of writing docker files and cleaning up things. Those docker files didn't make clear distinction about what gcc version was being used, whether the env was conda/non-conda etc. and that lead to ABI issues during conda packaging when I tried to use them. I hope you don't feel that I deleted them just without any reason.

**Conclusion**: I'll write the docker files based on what exists in repo currently that I wrote during the last release. I won't follow the long deleted ones because of reasons above.

**Comment by prigoyal** [comment]
for curiosity, those docker instructions you had shown looked like
```
curl -L https://github.com/docker/machine/releases/download/v0.13.0/docker-machine-`uname -s`-`uname -m` >/tmp/docker-machine && \
chmod +x /tmp/docker-machine && \
sudo cp /tmp/docker-machine /usr/local/bin/docker-machine

sudo apt-get install -y virtualbox virtualbox-ext-pack
sudo apt-get install -y virtualbox virtualbox-dkms virtualbox-guest-additions-iso virtualbox-guest-dkms 
sudo apt-get remove --purge virtualbox
sudo apt-get clean
sudo apt-get remove --purge docker.io





export TC_DOCKER=tc-1604-tapir5.0-src
cd ~/c2isl/docker/${TC_DOCKER} && \
docker-machine create -d virtualbox --virtualbox-memory 10000 --virtualbox-disk-size "30000" --virtualbox-cpu-count 16 --virtualbox-hostonly-nictype Am79C973 --virtualbox-nat-nictype Am79C973 ${TC_DOCKER} && \
docker-machine env ${TC_DOCKER} && \
eval $(docker-machine env ${TC_DOCKER}) && \
docker build -t nicolasvasilache/${TC_DOCKER} .

```

but I don't need to do this when I can simply do
```
docker build -t my_image:tag . 
```

**Comment by prigoyal** [comment]
also, I don't know if I ramped up in that meeting, we rather only ended up discussing the TC release 😆

**Comment by nicolasvasilache** [comment]
You're confusing 2 different things, one can use a preexisting ```docker``` installation if available or one can install one from scratch (which is what these commands do).

At the end of the road, there is no significant difference between the last line of the paste:
```
docker build -t nicolasvasilache/${TC_DOCKER} .
```
and 
```
docker build -t my_image:tag . 
```
but of course feel free to disagree.

All the rest is to install docker itself ...

Also, this is orthogonal to the dockerfiles. In any case if you have a better way that works for you, please use that; as always, best tool for the job.
I was sharing some insights about a procedure that worked in CI for months (without conda, which may indeed bring extra constraints that you know much better).
